---
on: [push]

env:
    REGISTRY: docker.io
    IMAGE_NAME: cosigncontainer

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        # Other build steps here
  
        - name: Install Cosign
          uses: sigstore/cosign-installer@main
  
        - name: Retrieve signing key from secrets
          run: echo "${{ secrets.COSIGN_PRIVATE_KEY }}" > cosign.key
  
        - name: Sign container image
          run: |
            cosign sign --key cosign.key \
              ${{ env.REGISTRY }}/blackadam12/${{ env.IMAGE_NAME }}:latest  
          env:
            COSIGN_PASSWORD: "${{ secrets.COSIGN_PASSWORD }}"